name = "Squidpack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9b988763eeef2a42e45a2e096da9cca2590cba1ca36d466c8f0ed6b33642961"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
