name = "Squidpack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16240dde724c01b2261a8fb485e81fdfacc3f0e1a69c3b16baa0ee417558720a"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
